# Configure.
services: [docker]
sudo: required

# Run.
before_install:
  - sudo tee /etc/udev/rules.d/85-vhba.rules <<< 'KERNEL=="vhba_ctl", MODE="0660", GROUP="travis"'
  - eval $(dbus-launch --sh-syntax)
install:
  - sudo add-apt-repository -y ppa:cdemu/ppa && sudo apt-get update
  - sudo apt-get install -y cdemu-client linux-headers-$(uname -r)
before_script:
  - docker build . -t robpol86/makemkv
script:
  - ./test.sh
