# Configure.
services: [docker]
sudo: required

# Run.
before_install:
  - sudo tee /etc/udev/rules.d/85-vhba.rules <<< 'KERNEL=="vhba_ctl", MODE="0660", GROUP="travis"'
  - eval $(dbus-launch --sh-syntax)
install:
  - sudo add-apt-repository -y ppa:cdemu/ppa && sudo apt-get update
  - sudo apt-get install -y cdemu-client linux-headers-$(uname -r)
  - cdemu load 0 sample.iso
script:
  - docker build . -t robpol86/makemkv
  - mkdir /tmp/MakeMKV
  - docker run -it --device=/dev/cdrom -e MKV_GID=$(id -g) -e MKV_UID=$(id -u) -v /tmp/MakeMKV:/output robpol86/makemkv
